package com.mcg.sofka.retotecnicobanco.api.rest.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * Aggregate root in the domain layer representing a person.
 *
 * <p>This entity encapsulates business data with validation, and it only exposes behavior through
 * getters/setters so application services can orchestrate manipulations via ports. Maintaining a dedicated
 * domain layer enforces the Dependency Inversion Principle and aligns with hexagonal architecture
 * by shielding adapters from internal rules.
 */
@Entity
@Table(name = "person")
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long personId;

    @Column(nullable = false, length = 80)
    private String firstName;

    @Column(nullable = false, length = 80)
    private String lastName;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private Gender gender;

    @Column(nullable = false)
    private Integer age;

    @Column(nullable = false, unique = true, length = 60)
    private String identification;

    @Column(nullable = false, length = 255)
    private String address;

    @Column(nullable = false, length = 30)
    private String phone;

    @Column(nullable = false)
    private OffsetDateTime createdAt;

    @Column(nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Domain enumeration for person gender.
     */
    public enum Gender {
        MALE,
        FEMALE,
        OTHER
    }

    /**
     * Returns the surrogate identifier generated by persistence.
     *
     * @return database identifier
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * Sets the persistence identifier. Typically managed by JPA and should not be mutated outside the repository.
     *
     * @param personId identifier
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * Returns the first name.
     *
     * @return first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Updates the first name, keeping the entity consistent for business rules applied elsewhere.
     *
     * @param firstName first name value
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Returns the last name.
     *
     * @return last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Updates the last name.
     *
     * @param lastName last name value
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Returns the configured gender enum.
     *
     * @return gender
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Updates the gender, which may be validated by application services before persisting.
     *
     * @param gender gender enum
     */
    public void setGender(Gender gender) {
        this.gender = gender;
    }

    /**
     * Returns the age value that business rules can enforce.
     *
     * @return age
     */
    public Integer getAge() {
        return age;
    }

    /**
     * Sets the age, enabling services to trigger validations (e.g., minimum age) before persistence.
     *
     * @param age age value
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Returns the unique identification string used in business rules and queries.
     *
     * @return identification
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * Sets the identification value that must remain unique as enforced by the repository/adapters.
     *
     * @param identification identification value
     */
    public void setIdentification(String identification) {
        this.identification = identification;
    }

    /**
     * Returns the address detail.
     *
     * @return address
     */
    public String getAddress() {
        return address;
    }

    /**
     * Updates the address field, with any further validation performed by services or infrastructure.
     *
     * @param address address value
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Returns the phone detail stored in the entity.
     *
     * @return phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Updates the phone number.
     *
     * @param phone phone number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Returns the creation timestamp managed by services or adapters.
     *
     * @return creation timestamp
     */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Assigns the creation timestamp.
     *
     * @param createdAt creation time
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Returns the last update timestamp.
     *
     * @return update time
     */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the update timestamp, typically refreshed by the service layer before persistence.
     *
     * @param updatedAt update time
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
